### ISSUE TITLE
Runtime Totals Reporting

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.API.Client#5]
- [ ] 1  Need to Calculate Total Bytes From Flickr API (Photo Byte Size)

  - [x] 2 Terminate Running Program (ctrl-c)  and display process stats for completed results

The Following query will run a long time (2000+ Images Results)
```
MachineTags = "machine_tags => nycparks:",
```
  - [ ] 3  Query will complete and never display Runtime results (This does not happen on every run)

![capture](https://user-images.githubusercontent.com/887805/45333812-f609ac00-b545-11e8-87d4-1ccba353f8f6.PNG)

![untitled](https://user-images.githubusercontent.com/887805/45260478-e740bf00-b3b6-11e8-94a1-53a034392b38.png)

![untitled](https://user-images.githubusercontent.com/887805/45260498-6fbf5f80-b3b7-11e8-9444-8fc8dcf6164f.png)

Print Report Totals on Run Completion

![untitled](https://user-images.githubusercontent.com/887805/45260527-3fc48c00-b3b8-11e8-9489-a42d8cc93679.png)

**Comment by panthernet** [comment]
Implemented and commited the code

**Comment by panthernet** [comment]
Seems like there are issues with post performance when there are many images received from previous api calls.  Lowering threads count helps. I'm not sure how the flickr library implements the concurrency and api calls (in terms of heavy load), there might be issues I can't predict. Now I've lowered overall threads count used in app but performance should stay approximately the same.

**Comment by stuartshay** [comment]
I think there is a issue with the max allowed bytes transferred for the images, Flickr is throttling the allow bytes transferred, 

Most likely need to implement some retry logic, I know this framework provides this logic, might need to investigate this 
http://www.thepollyproject.org/

**Comment by panthernet** [comment]
Yeah, seems like Flickr issue. I just had the first run passed fast and the second one starts to hang.

**Comment by panthernet** [comment]
Added cancellation support
