### ISSUE TITLE
Retry Logic - HTTP Client Factory/Polly

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.API.Client#6]
Implement httpclientFactory - (This Looks Cleaner)

https://csharp.christiannagel.com/2018/06/05/httpclient/

#### Section 8
https://blogs.msdn.microsoft.com/cesardelatorre/2017/05/10/free-ebookguide-on-net-microservices-architecture-for-containerized-net-applications/

https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore

```
services.AddHttpClient("token", client =>
services.AddHttpClient("flickrsearch", client =>
services.AddHttpClient("imagegallery", client =>
```

See
https://github.com/App-vNext/Polly

**Comment by panthernet** [comment]
Implemented

**Comment by stuartshay** [comment]
I think this might be a cleaner solution
https://csharp.christiannagel.com/2018/06/05/httpclient/

**Comment by stuartshay** [comment]
Added HTTP Client Factory Code Much Faster !!!
